In [1]:
import numpy as np
import torch

In [2]:
x = np.ones((2,3))
y = torch.zeros(2,3)

In [3]:
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
y

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])

In [5]:
z = x + y
z

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)

In [6]:
xx = z.numpy()
xx +=2
print(xx)

[[3. 3. 3.]
 [3. 3. 3.]]


In [7]:
torch.Tensor([3,2])*torch.Tensor([[0,1],[4,2]])

tensor([[  0.,   2.],
        [ 12.,   4.]])

In [8]:
from torch.autograd import Variable
v = Variable(torch.ones(1, 2), requires_grad=True)

In [9]:
print(v.data)     #  1  1 [torch.FloatTensor of size 1x2]
print(v.grad)     # None
print(v.grad_fn)  # None

tensor([[ 1.,  1.]])
None
None


In [10]:
v_fn = torch.sum(v ** 2)
print(v_fn.data)    # 2 [torch.FloatTensor of size 1]
print(v_fn.grad_fn) # <SumBackward0 object at 0x7fa959f21550>

tensor(2.)


In [11]:
torch.autograd.grad(v_fn, v)

(tensor([[ 2.,  2.]]),)

In [12]:
v1 = Variable(torch.Tensor([1, 2]), requires_grad=True)
v2 = Variable(torch.Tensor([3]), requires_grad=True)
v_fn = torch.sum(v1 * v2)

In [13]:
v_fn.backward()
print(v1.grad) # Variable containing: 3 3 [torch.FloatTensor of size 2x1]
print(v2.grad)

tensor([ 3.,  3.])
tensor([ 3.])


## Regressione lineare 

In [14]:
X = np.random.rand(30, 1)*2.0
w = np.random.rand(2, 1)
y = X*w[0] + w[1] + np.random.randn(30, 1) * 0.05

In [15]:
W = Variable(torch.rand(1, 1), requires_grad=True)
b = Variable(torch.rand(1), requires_grad=True)

def linear(x):
  return torch.matmul(x, W) + b

In [16]:
Xt = Variable(torch.from_numpy(X)).float()
yt = Variable(torch.from_numpy(y)).float()

for epoch in range(2500):

  # Calcola le predizioni
  y_pred = linear(Xt)

  # Calcola funzione costo
  loss = torch.mean((y_pred - yt) ** 2)

  # Esegui back-propagation
  loss.backward()

  # Aggiorna le variabili
  W.data = W.data - 0.005*W.grad.data
  b.data = b.data - 0.005*b.grad.data

  # Resetta il gradiente
  W.grad.data.zero_()
  b.grad.data.zero_()

In [18]:
from sklearn.decomposition import DictionaryLearning

In [20]:
y = np.ones((100,1))

In [22]:
y[np.random.randint(0,100,50)] = 0

In [23]:
dl = DictionaryLearning(n_components=1000)

In [26]:
dl.fit(y)
coeff = dl.transform(y)

/home/vero/git_repos/scikit-learn/sklearn/decomposition/dict_learning.py:160: RuntimeWarning:  Orthogonal matching pursuit ended prematurely due to linear
dependence in the dictionary. The requested precision might not have been met.

  copy_Xy=copy_cov).T


In [25]:
dl.components_

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
      

In [27]:
coeff

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])